FROM {{ .nginxImage }}

COPY mime.types /etc/nginx/mime.types
COPY nginx.docker.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d

RUN rm -f /etc/nginx/conf.d/default.conf

EXPOSE {{ .proxyPort }}

CMD ["nginx", "-g", "daemon off;"]